const reqEvent = (event) => require(`../events/${event}`);
module.exports = (client) => {
  client.on("ready", () => reqEvent("ready")(client));
  client.on("reconnecting", () => reqEvent("reconnecting")(client));
  client.on("disconnect", () => reqEvent("disconnect")(client));
  client.on("messageCreate", reqEvent("messageCreate"));
  client.on("guildMemberAdd", reqEvent("guildMemberAdd"));
  client.on("guildMemberRemove", reqEvent("guildMemberRemove"));
  client.on("channelCreate", reqEvent("channelCreate"));
  client.on("channelDelete", reqEvent("channelDelete"));
  client.on("guildCreate", reqEvent("guildCreate"));
  client.on("guildDelete", reqEvent("guildDelete"));
  client.on("messageDelete", reqEvent("messageDelete"));
  client.on("messageUpdate", reqEvent("messageUpdate"));
  client.on("roleCreate", reqEvent("roleCreate"));
  client.on("roleDelete", reqEvent("roleDelete"));
  client.on("userUpdate", reqEvent("userUpdate"));
  client.on("roleUpdate", reqEvent("roleUpdate"));
  client.on("messageReactionAdd", reqEvent("messageReactionAdd"));
  client.on("messageReactionRemove", reqEvent("messageReactionRemove"));
  client.on("interactionCreate", reqEvent("interactionCreate"));
};
